#ifndef _CCB_CCBREADER_H_
#define _CCB_CCBREADER_H_

#include <string>
#include <vector>
#include "2d/CCNode.h"
#include "base/CCData.h"
#include "base/CCMap.h"
#include "CCBSequence.h"
#include "extensions/GUI/CCControlExtension/CCControl.h"

#define CCB_STATIC_NEW_AUTORELEASE_OBJECT_METHOD(T, METHOD) static T * METHOD() { \
    T * ptr = new T(); \
    if(ptr != NULL) { \
        ptr->autorelease(); \
        return ptr; \
    } \
    CC_SAFE_DELETE(ptr); \
    return NULL; \
}

#define CCB_STATIC_NEW_AUTORELEASE_OBJECT_WITH_INIT_METHOD(T, METHOD) static T * METHOD() { \
    T * ptr = new T(); \
    if(ptr != NULL && ptr->init()) { \
        ptr->autorelease(); \
        return ptr; \
    } \
    CC_SAFE_DELETE(ptr); \
    return NULL; \
}

#define CCB_MIN_VERSION 5
#define CCB_MAX_VERSION 6

#define CCBX_MIN_VERSION 7
#define CCBX_MAX_VERSION 8

namespace cocosbuilder {

/**
 * @addtogroup cocosbuilder
 * @{
 */

class CCBFile : public cocos2d::Node
{
private:
    cocos2d::Node *_CCBFileNode;
    
public:
    CCBFile();
    
    static CCBFile* create();
    
    cocos2d::Node* getCCBFileNode();
    void setCCBFileNode(Node *pNode); // retain
};

/* Forward declaration. */
class NodeLoader;
class NodeLoaderLibrary;
class NodeLoaderListener;
class CCBMemberVariableAssigner;
class CCBSelectorResolver;
class CCBAnimationManager;
class CCBKeyframe;

/**
 * @brief Parse CCBI file which is generated by CocosBuilder
 */
class CCBReader : public cocos2d::Ref 
{
public:
    enum class PropertyType {
        POSITION = 0,
        SIZE,
        POINT,
        POINT_LOCK,
        SCALE_LOCK,
        DEGREES,
        INTEGER,
        FLOAT,
        FLOAT_VAR,
        CHECK,
        SPRITEFRAME,
        TEXTURE,
        BYTE,
        COLOR3,
        COLOR4F_VAR,
        FLIP,
        BLEND_MODE,
        FNT_FILE,
        TEXT,
        FONT_TTF,
        INTEGER_LABELED,
        BLOCK,
        ANIMATION,
        CCB_FILE,
        STRING,
        BLOCK_CONTROL,
        FLOAT_SCALE,
        FLOAT_XY,
        COLOR4,
        CCB_FILE_NAME
    };
    
    enum class FloatType {
        _0 = 0,
        _1,
        MINUS1,
        _05,
        INTEGER,
        FULL
    };
    
    enum class PlatformType {
        ALL = 0,
        IOS,
        MAC
    };
    
    enum class TargetType {
        NONE = 0,
        DOCUMENT_ROOT = 1,
        OWNER = 2,
    };
    
    enum class PositionType
    {
        RELATIVE_BOTTOM_LEFT,
        RELATIVE_TOP_LEFT,
        RELATIVE_TOP_RIGHT,
        RELATIVE_BOTTOM_RIGHT,
        PERCENT,
        MULTIPLY_RESOLUTION,
    };
   
    enum class PositionUnit
    {
        /// Position is set in points (this is the default)
        POINTS,
        
        /// Position is UI points, on iOS this corresponds to the native point system
        UIPOINTS,
        
        /// Position is a normalized value multiplied by the content size of the parent's container
        NORMALIZED,
        
    };
    
    enum class PositionReferenceCorner
    {
        /// Position is relative to the bottom left corner of the parent container (this is the default)
        BOTTOMLEFT,
        
        /// Position is relative to the top left corner of the parent container
        TOPLEFT,
        
        /// Position is relative to the top right corner of the parent container
        TOPRIGHT,
        
        /// Position is relative to the bottom right corner of the parent container
        BOTTOMRIGHT,
    };
    
    enum class SizeUnit
    {
        /// Content size is set in points (this is the default)
        POINTS,
        
        /// Position is UI points, on iOS this corresponds to the native point system
        UIPOINTS,
        
        /// Content size is a normalized value multiplied by the content size of the parent's container
        NORMALIZED,
        
        /// Content size is the size of the parents container inset by the supplied value
        INSETPOINTS,
        
        /// Content size is the size of the parents container inset by the supplied value multiplied by the UIScaleFactor (as defined by CCDirector)
        INSETUIPOINTS,
        
    };
    
   
#if CC_TARGET_PLATFORM == CC_PLATFORM_WP8
#ifdef ABSOLUTE
#undef ABSOLUTE
#endif
#endif

    enum class SizeType
    {
        ABSOLUTE,
        PERCENT,
        RELATIVE_CONTAINER,
        HORIZONTAL_PERCENT,
        VERTICAL_PERCENT,
        MULTIPLY_RESOLUTION,
    };
    
    enum class ScaleType
    {
        ABSOLUTE = 0,
        MULTIPLY_RESOURCES_SCALE = 1,
        MULTIPLY_MAIN_SCALE = 2,
        MULTIPLY_ADDITION_SCALE_X = 4,
        MULTIPLY_ADDITION_SCALE_Y = 8,
        INVERT_SCALE = 16,
    };
    
    enum class SceneScaleType
    {
        NONE,
        CUSTOM,
        MINSIZE,
        MAXSIZE,
        MINSCALE,
        MAXSCALE
    };
    /**
     * @js NA
     * @lua NA
     */
    CCBReader(NodeLoaderLibrary *pNodeLoaderLibrary, CCBMemberVariableAssigner *pCCBMemberVariableAssigner = NULL, CCBSelectorResolver *pCCBSelectorResolver = NULL, NodeLoaderListener *pNodeLoaderListener = NULL);
    /**
     * @js NA
     * @lua NA
     */
    CCBReader(CCBReader *ccbReader);
    /**
     * @js NA
     * @lua NA
     */
    virtual ~CCBReader();
    /**
     * @js NA
     * @lua NA
     */
    CCBReader();
   
    void setCCBRootPath(const char* ccbRootPath);
    const std::string& getCCBRootPath() const;
    
    void calcScales(const cocos2d::Size &designResolution, float designScale, SceneScaleType scaleType);

    cocos2d::Node* readNodeGraphFromFile(const std::string &pCCBFileName, SceneScaleType scaleType = SceneScaleType::NONE);
    cocos2d::Node* readNodeGraphFromFile(const std::string &pCCBFileName, cocos2d::Ref *pOwner, SceneScaleType scaleType = SceneScaleType::NONE);
    cocos2d::Node* readNodeGraphFromFile(const std::string &pCCBFileName, cocos2d::Ref *pOwner, const cocos2d::Size &parentSize, SceneScaleType scaleType = SceneScaleType::NONE);
    /**
     * @js NA
     * @lua NA
     */
    cocos2d::Node* readNodeGraphFromData(const cocos2d::Data &data, SceneScaleType scaleType = SceneScaleType::NONE);
    cocos2d::Node* readNodeGraphFromData(const cocos2d::Data &data, cocos2d::Ref *pOwner, SceneScaleType scaleType = SceneScaleType::NONE);
    cocos2d::Node* readNodeGraphFromData(const cocos2d::Data &data, cocos2d::Ref *pOwner, const cocos2d::Size &parentSize, SceneScaleType scaleType = SceneScaleType::NONE);
   
    /**
     @lua NA
     */
    cocos2d::Scene* createSceneWithNodeGraphFromFile(const std::string &pCCBFileName, SceneScaleType scaleType = SceneScaleType::NONE);
    /**
     @lua NA
     */
    cocos2d::Scene* createSceneWithNodeGraphFromFile(const std::string &pCCBFileName, cocos2d::Ref *pOwner, SceneScaleType scaleType = SceneScaleType::NONE);
    /**
     @lua NA
     */
    cocos2d::Scene* createSceneWithNodeGraphFromFile(const std::string &pCCBFileName, cocos2d::Ref *pOwner, const cocos2d::Size &parentSize, SceneScaleType scaleType = SceneScaleType::NONE);
    
    /**
     * @js NA
     * @lua NA
     */
    CCBMemberVariableAssigner* getCCBMemberVariableAssigner();
    /**
     * @js NA
     * @lua NA
     */
    CCBSelectorResolver* getCCBSelectorResolver();
    
    /**
     * @js getActionManager
     * @lua getActionManager
     */
    CCBAnimationManager* getAnimationManager();
    /**
     * @js setActionManager
     * @lua setActionManager
     */
    void setAnimationManager(CCBAnimationManager *pAnimationManager);
    
    /**  Used in NodeLoader::parseProperties()
     * @js NA
     * @lua NA
     */
    std::set<std::string>* getAnimatedProperties();
    /**
     * @js NA
     * @lua NA
     */
    std::set<std::string>& getLoadedSpriteSheet();
    /**
     * @js NA
     * @lua NA
     */
    cocos2d::Ref* getOwner();

    /* Utility methods. 
     * @js NA
     * @lua NA
     */
    static std::string lastPathComponent(const char* pString);
    /**
     * @js NA
     * @lua NA
     */
    static std::string deletePathExtension(const char* pString);
    /**
     * @js NA
     * @lua NA
     */
    static std::string toLowerCase(const char* pString);
    /**
     * @js NA
     * @lua NA
     */
    static bool endsWith(const char* pString, const char* pEnding);

    /* Parse methods. 
     * @js NA
     * @lua NA
     */
    int readInt(bool pSigned);
    /**
     * @js NA
     * @lua NA
     */
    unsigned char readByte();
    /**
     * @js NA
     * @lua NA
     */
    bool readBool();
    std::string readUTF8();
    /**
     * @js NA
     * @lua NA
     */
    float readFloat();
    /**
     * @js NA
     * @lua NA
     */
    const std::string& readCachedString();
    /**
     * @js NA
     * @lua NA
     */
    bool isJSControlled();
    
    bool readCallbackKeyframesForSeq(CCBSequence* seq);
    bool readSoundKeyframesForSeq(CCBSequence* seq);
    
    cocos2d::ValueVector getOwnerCallbackNames();
    cocos2d::Vector<cocos2d::Node*>& getOwnerCallbackNodes();
    cocos2d::ValueVector& getOwnerCallbackControlEvents();
    
    cocos2d::ValueVector getOwnerOutletNames();
    cocos2d::Vector<cocos2d::Node*>& getOwnerOutletNodes();
    cocos2d::Vector<cocos2d::Node*>& getNodesWithAnimationManagers();
    cocos2d::Vector<CCBAnimationManager*>& getAnimationManagersForNodes();
    
    typedef cocos2d::Map<cocos2d::Node*, CCBAnimationManager*> CCBAnimationManagerMap;
    typedef std::shared_ptr<CCBAnimationManagerMap> CCBAnimationManagerMapPtr;
    
    /**
     * @js NA
     * @lua NA
     */
    CCBAnimationManagerMapPtr getAnimationManagers();
    /**
     * @js NA
     * @lua NA
     */
    void setAnimationManagers(CCBAnimationManagerMapPtr x);
    /**
     * @js NA
     * @lua NA
     */
    void addOwnerCallbackName(const std::string& name);
    /**
     * @js NA
     * @lua NA
     */
    void addOwnerCallbackNode(cocos2d::Node *node);
    void addOwnerCallbackControlEvents(cocos2d::extension::Control::EventType type);
    /**
     * @js NA
     * @lua NA
     */
    void addDocumentCallbackName(const std::string& name);
    /**
     * @js NA
     * @lua NA
     */
    void addDocumentCallbackNode(cocos2d::Node *node);
    void addDocumentCallbackControlEvents(cocos2d::extension::Control::EventType eventType);
    /**
     * @js NA
     * @lua NA
     */
    static float getResolutionScale();
    static void setResolutionScale(float scale);
    /**
     * @js NA
     * @lua NA
     */
    float getMainScale();
    void setMainScale(float scale);
    /**
     * @js NA
     * @lua NA
     */
    float getAdditionalScale();
    void setAdditionalScale(float scale);
    /**
     * @js NA
     * @lua NA
     */
    cocos2d::Node* readFileWithCleanUp(bool bCleanUp, CCBAnimationManagerMapPtr am);
    
    int getVersion() const { return _version; }
    bool isCCBX() const { return _ccbx; }
    
    void addOwnerOutletName(std::string name);
    void addOwnerOutletNode(cocos2d::Node *node);

private:
    void cleanUpNodeGraph(cocos2d::Node *pNode);
    bool readSequences();
    CCBKeyframe* readKeyframe(PropertyType type);
    
    bool readHeader();
    bool readStringCache();
    //void readStringCacheEntry();
    cocos2d::Node* readNodeGraph();
    cocos2d::Node* readNodeGraph(cocos2d::Node * pParent);

    bool getBit();
    void alignBits();

    bool init();
    
    friend class NodeLoader;

private:
    unsigned char *_bytes;
    int _currentByte;
    int _currentBit;
    int _version;
    
    std::vector<std::string> _stringCache;
    std::set<std::string> _loadedSpriteSheets;
    
    cocos2d::Ref *_owner;
    
    CCBAnimationManager* _animationManager; //retain
    CCBAnimationManagerMapPtr _animationManagers;
    
    std::set<std::string> *_animatedProps;
    
    NodeLoaderLibrary *_nodeLoaderLibrary;
    NodeLoaderListener *_nodeLoaderListener;
    CCBMemberVariableAssigner *_CCBMemberVariableAssigner;
    CCBSelectorResolver *_CCBSelectorResolver;
    
    std::vector<std::string> _ownerOutletNames;
    cocos2d::Vector<cocos2d::Node*> _ownerOutletNodes;
    cocos2d::Vector<cocos2d::Node*> _nodesWithAnimationManagers;
    cocos2d::Vector<CCBAnimationManager*> _animationManagersForNodes;
    
    std::vector<std::string> _ownerCallbackNames;
    cocos2d::Vector<cocos2d::Node*> _ownerCallbackNodes;
    cocos2d::ValueVector _ownerOwnerCallbackControlEvents;
    std::string _CCBRootPath;
    
    bool _jsControlled;
    bool _ccbx;
    float _ccbMainScale;
    float _ccbAdditionalScale;
};

// end of effects group
/// @}

}

#endif
